name: Go

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: dk251626910
        password: 885a4287-3def-40a8-b203-86a45563b914
        
    - name: build image
      env:
        REP: dk251626910/ffl-user-svc
      run: |
        docker build -t $REP .
        docker push $REP
    
      
